services:
  ws-server:
    build:
      context: ./apps/ws-server
    ports:
      - "3001:3001"
    networks:
      - fcn-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  http-server:
    build:
      context: ./apps/http-server
    ports:
      - "3002:3002"
    networks:
      - fcn-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build:
      context: ./apps/web
    ports:
      - "3000:3000"
    networks:
      - fcn-network
    depends_on:
      ws-server:
        condition: service_healthy
      http-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - fcn-network
    depends_on:
      web:
        condition: service_healthy
      http-server:
        condition: service_healthy
      ws-server:
        condition: service_healthy

networks:
  fcn-network:
    driver: bridge
