services:
  ws-server:
    image: faithfulconnects/ws-server:${IMAGE_TAG}
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    container_name: ws-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "3001:3001"
    networks:
      - fcn-network
    environment:
      - FCN_DATABASE_URL=${FCN_DATABASE_URL}

  http-server:
    image: faithfulconnects/http-server:${IMAGE_TAG}
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    container_name: http-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "3002:3002"
    networks:
      - fcn-network
    environment:
      - FCN_DATABASE_URL=${FCN_DATABASE_URL}

  web:
    image: faithfulconnects/web:${IMAGE_TAG}
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    container_name: web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "3000:3000"
    networks:
      - fcn-network
    environment:
      - FCN_DATABASE_URL=${FCN_DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

networks:
  fcn-network:
    driver: bridge
