services:
  turbo-repo:
    image: faithfulconnects/turbo-repo:${IMAGE_TAG}
    container_name: turbo-repo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "3000:3000" # Next.js app
      - "3001:3001" # WebSocket server
      - "3002:3002" # HTTP server
    networks:
      - fcn-network
    environment:
      - FCN_DATABASE_URL=${FCN_DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

networks:
  fcn-network:
    driver: bridge
