FROM node:22-alpine

ENV NODE_ENV=development

# https://github.com/vercel/turbo/issues/2198
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

# Install pnpm and turbo globally
RUN npm install -g pnpm turbo

# Set working directory
WORKDIR /app

# Copy package files first to leverage Docker caching
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# Install dependencies
RUN pnpm install

# Copy source files
COPY . .

EXPOSE 3000 3001 3002

# Run development servers using Turborepo
CMD ["pnpm", "turbo", "dev"]