name: Deploy Nginx with SSL

on:
  pull_request:
    types: [opened]
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday at midnight

jobs:
  setup-nginx-ssl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEV_PRIVATE_KEY }}

      - name: Deploy SSL and Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_DEV_USERNAME }}@${{ secrets.SSH_DEV_HOST }} << 'EOF'
            # Update system and install Certbot
            sudo apt update && sudo apt install -y certbot python3-certbot-nginx

            # Ensure Nginx is installed
            sudo apt install -y nginx
            
            # Check if SSL certificates already exist
            if [ ! -f "/etc/letsencrypt/live/dev.fcn.social/fullchain.pem" ]; then
              echo "Generating SSL Certificates..."
              sudo certbot certonly --nginx -d dev.fcn.social -d api.dev.fcn.social -d ws.dev.fcn.social --non-interactive --agree-tos -m ${{ secrets.SSL_EMAIL }}
            else
              echo "SSL Certificates already exist."
            fi

            # Deploy new Nginx configuration
            sudo mkdir -p /home/${{ secrets.SSH_DEV_USERNAME }}/nginx
            sudo touch /home/${{ secrets.SSH_DEV_USERNAME }}/nginx/nginx.conf
            echo "${{ secrets.NGINX_CONFIG }}" | sudo tee /home/${{ secrets.SSH_DEV_USERNAME }}/nginx/nginx.conf > /dev/null
            sudo mv /home/${{ secrets.SSH_DEV_USERNAME }}/nginx/nginx.conf /etc/nginx/nginx.conf

            # Restart Nginx
            sudo systemctl restart nginx

            # Schedule SSL auto-renewal
            (crontab -l ; echo "0 0 * * 1 certbot renew --quiet --renew-hook 'systemctl restart nginx'") | crontab -

            echo "✅ Deployment and SSL setup completed."
          EOF
